
spring:
  datasource:
    url: jdbc:postgresql://dpg-cq4l8v88fa8c73fre7rg-a.oregon-postgres.render.com:5432/postgres
    username: hngauth
    password: WDUI7X8aLsVDCpoOyJ2FpN0DTwH5jA42
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


